# Makefile for mock ML project
#!/bin/bash

# Make predictions
predict:
	python src/predict.py

#Make preprocess
preprocess:
	python src/preprocess.py

#Start docker
build-docker:
	docker build -t mock_ml_image .

